"""Materials MCP Commons engine package."""

from importlib.metadata import version

from .authoring import (
    ENGINE_REQUIREMENT,
    CapabilitySpec,
    EffectSpec,
    ExtensionSpec,
    PackageReceipt,
    PluginPackageBuilder,
    PluginPackageSpec,
    ScaffoldReceipt,
    SchemaSpec,
    WorkspaceSpec,
    scaffold_workspace,
)
from .context import (
    CompactProjection,
    ContextGateway,
    ContextMeasurement,
    ContextPolicy,
    ContextReport,
    ContextViolation,
    LifecycleWorkloadReport,
    RetrievalCase,
    RetrievalReport,
    canonical_json,
    card_document,
    evaluate_retrieval,
    run_lifecycle_workload,
)
from .contracts import ContractRegistry
from .control import DISCOVER_CAPABILITY_ID, INSPECT_CAPABILITY_ID, EngineControlHandlers
from .dispatch import (
    MAX_DISPATCH_PAYLOAD_BYTES,
    MAX_DISPATCH_PAYLOAD_DEPTH,
    MAX_DISPATCH_PAYLOAD_NODES,
    Dispatcher,
    DispatchFailure,
    DispatchOutcome,
    DispatchRequest,
    DispatchSuccess,
    HandlerBinding,
    HandlerRequest,
)
from .errors import (
    AuthoringError,
    CommonsError,
    ContextError,
    ContractError,
    DispatchError,
    HostError,
    LifecycleError,
    PluginConformanceError,
    PolicyError,
    RunStoreError,
    StateRecoveryError,
)
from .lifecycle import (
    Activation,
    ActiveCapabilityTarget,
    CapabilityCard,
    CapabilityDetail,
    CapabilityTarget,
    LifecyclePolicy,
    LifecycleRegistry,
    Registration,
)
from .manifest import Capability, Effect, LoadedManifest, ManifestLoader, SchemaResource
from .mcp_host import (
    PUBLIC_MCP_ERROR_CODES,
    AuthorizationResolver,
    EngineMCPHost,
    HostHealth,
    create_mcp_server,
)
from .operations import (
    EventSink,
    OperationEvent,
    OperationMetric,
    OperationMetricsSnapshot,
    OperationObserver,
)
from .plugin_conformance import (
    MigrationAssessment,
    PackageCase,
    PluginConformanceReport,
    PluginConformanceRunner,
    ProfileCase,
    VersionedConformanceMatrix,
    assess_plugin_migration,
    build_versioned_matrix,
    capability_reference_sha256,
    plugin_conformance_main,
    render_capability_reference,
    serialize_plugin_report,
)
from .policy import (
    ApprovalRecord,
    AuditEvent,
    AuthorizationGrant,
    AuthorizationReceipt,
    OperationPlan,
    Permission,
    PolicyEngine,
    PolicySnapshot,
    QuotaCharge,
    QuotaLimit,
)
from .runs import ArtifactAttachment, ArtifactSnapshot, RunOwner, RunSnapshot, RunStore
from .state_recovery import DatabaseSnapshot, RecoveryLimits, StateRecovery, StateSnapshot

__version__: str = version("materials-mcp-commons")

__all__ = (
    "DISCOVER_CAPABILITY_ID",
    "ENGINE_REQUIREMENT",
    "INSPECT_CAPABILITY_ID",
    "MAX_DISPATCH_PAYLOAD_BYTES",
    "MAX_DISPATCH_PAYLOAD_DEPTH",
    "MAX_DISPATCH_PAYLOAD_NODES",
    "PUBLIC_MCP_ERROR_CODES",
    "Activation",
    "ActiveCapabilityTarget",
    "ApprovalRecord",
    "ArtifactAttachment",
    "ArtifactSnapshot",
    "AuditEvent",
    "AuthoringError",
    "AuthorizationGrant",
    "AuthorizationReceipt",
    "AuthorizationResolver",
    "Capability",
    "CapabilityCard",
    "CapabilityDetail",
    "CapabilitySpec",
    "CapabilityTarget",
    "CommonsError",
    "CompactProjection",
    "ContextError",
    "ContextGateway",
    "ContextMeasurement",
    "ContextPolicy",
    "ContextReport",
    "ContextViolation",
    "ContractError",
    "ContractRegistry",
    "DatabaseSnapshot",
    "DispatchError",
    "DispatchFailure",
    "DispatchOutcome",
    "DispatchRequest",
    "DispatchSuccess",
    "Dispatcher",
    "Effect",
    "EffectSpec",
    "EngineControlHandlers",
    "EngineMCPHost",
    "EventSink",
    "ExtensionSpec",
    "HandlerBinding",
    "HandlerRequest",
    "HostError",
    "HostHealth",
    "LifecycleError",
    "LifecyclePolicy",
    "LifecycleRegistry",
    "LifecycleWorkloadReport",
    "LoadedManifest",
    "ManifestLoader",
    "MigrationAssessment",
    "OperationEvent",
    "OperationMetric",
    "OperationMetricsSnapshot",
    "OperationObserver",
    "OperationPlan",
    "PackageCase",
    "PackageReceipt",
    "Permission",
    "PluginConformanceError",
    "PluginConformanceReport",
    "PluginConformanceRunner",
    "PluginPackageBuilder",
    "PluginPackageSpec",
    "PolicyEngine",
    "PolicyError",
    "PolicySnapshot",
    "ProfileCase",
    "QuotaCharge",
    "QuotaLimit",
    "RecoveryLimits",
    "Registration",
    "RetrievalCase",
    "RetrievalReport",
    "RunOwner",
    "RunSnapshot",
    "RunStore",
    "RunStoreError",
    "ScaffoldReceipt",
    "SchemaResource",
    "SchemaSpec",
    "StateRecovery",
    "StateRecoveryError",
    "StateSnapshot",
    "VersionedConformanceMatrix",
    "WorkspaceSpec",
    "__version__",
    "assess_plugin_migration",
    "build_versioned_matrix",
    "canonical_json",
    "capability_reference_sha256",
    "card_document",
    "create_mcp_server",
    "evaluate_retrieval",
    "plugin_conformance_main",
    "render_capability_reference",
    "run_lifecycle_workload",
    "scaffold_workspace",
    "serialize_plugin_report",
)
